name: CI with Dependency Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cache Python dependencies
      - name: prime-cache-f4a9540
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f4a9540
          restore-keys: cache-f4a9540

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests (optional)
      - name: Run tests
        run: echo "CI step executed"
