name: Cache Dependencies Demo

on:
  workflow_dispatch:
  push:

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Cache pip dependencies
      - name: Cache pip dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f4a9540
          restore-keys: |
            cache-

      # Step 4: Prime cache step (exact name required)
      - name: prime-cache-f4a9540
        run: |
          echo "Cache hit status: ${{ steps.cache.outputs.cache-hit }}"

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 6: Verification script
      - name: Run verification script
        run: python -c "import requests; print('Cache demo complete ✅')"
