name: 21f3001224@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  daily-commit-job-21f3001224:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add daily commit 21f3001224@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily_update.txt
          git config --local user.email "21f3001224@ds.study.iitm.ac.in"
          git config --local user.name "Auto Commit Bot"
          git add daily_update.txt
          git commit -m "Daily automated commit" || echo "No changes to commit"

      - name: Push commit to repo 21f3001224@ds.study.iitm.ac.in
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
